In [1]:

import pandas as pd
import pyodbc 

server = 'EDMILSON\MSSQL' # Substitua pelo nome do servidor SQL Server
database = 'Python'  # Substitua pelo nome do banco de dados
conexaoDB = pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server};'
                      f'SERVER={server};'
                      f'DATABASE={database};'
                      'Trusted_Connection=yes;')

cursor = conexaoDB.cursor()   # criando cursor de comando '

In [3]:
Query = """

select 
t1.id as IdVenda
,t3.Nome as Produto
,t4.Categoria
,t1.total_price
,t2.status
,t2.created_at
,t5.first_name as NomeCliente
,t5.email
,t5.cell_phone as Telefone
,t5.state as Estado
from [dbo].[Items]									as T1	
Left Join  [dbo].[Ordens]						as T2 on t1.order_id = t2.id
Left join [dbo].[Produtos]					as T3 on t1.product_id= t3.ID
Left join [dbo].[Categoria]					as T4 on t3.Id_Category = t4.ID
Left join [dbo].[Clientes]				        as T5 on t2.customer_id = t5.id


"""

In [6]:
Join = pd.read_sql(Query,conexaoDB)
Join.head(10)

C:\Users\edmil\AppData\Local\Temp\ipykernel_14204\2881997810.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  Join = pd.read_sql(Query,conexaoDB)

,IdVenda,Produto,Categoria,total_price,status,created_at,NomeCliente,email,Telefone,Estado
0,10682,Máquina Fotográfica,Eletrônicos,377.0,entregue,2019-08-28 03:36:31,Daniel,daniel@teste.com,9 4761-6557,Rio Grande do Norte
1,15650,Hidratante caro,Cosméticos e Perfumaria,10.0,entregue,2019-08-28 03:36:31,Daniel,daniel@teste.com,9 4761-6557,Rio Grande do Norte
2,19082,A Comédia Engraçada,Livros,20.0,entregue,2019-08-28 03:36:31,Daniel,daniel@teste.com,9 4761-6557,Rio Grande do Norte
3,26312,O Romance Exagerado,Livros,92.0,entregue,2019-08-28 03:36:31,Daniel,daniel@teste.com,9 4761-6557,Rio Grande do Norte
4,26347,Chiai-homi,Celulares,2304.0,entregue,2019-08-28 03:36:31,Daniel,daniel@teste.com,9 4761-6557,Rio Grande do Norte
5,43593,Fogão,Eletrodomésticos,4119.0,entregue,2019-08-28 03:36:31,Daniel,daniel@teste.com,9 4761-6557,Rio Grande do Norte
6,13271,Terror Aterrorizante,Livros,45.0,entregue,2019-08-16 20:21:30,Everton,everton@meu_email.com,9 2553-4087,Distrito Federal
7,19379,Shampoo,Cosméticos e Perfumaria,15.0,entregue,2019-08-16 20:21:30,Everton,everton@meu_email.com,9 2553-4087,Distrito Federal
8,27811,Creme de Barbear,Cosméticos e Perfumaria,30.0,entregue,2019-08-16 20:21:30,Everton,everton@meu_email.com,9 2553-4087,Distrito Federal
9,34234,Vestido Super curto,Moda e Acessórios,57.0,entregue,2019-08-16 20:21:30,Everton,everton@meu_email.com,9 2553-4087,Distrito Federal